//
// Created by cyberxix on 16.02.16.
//

#ifndef GEARRAKE_CONSTANTS_MESSAGE_H
#define GEARRAKE_CONSTANTS_MESSAGE_H

#define CONF_MESSAGE_LEN 5

enum MessageTypes{
    MESSAGE_NONE,
    MESSAGE_TIMOUT_REQUEST,
    MESSAGE_TIMER_REQUEST,
    MESSAGE_CYLINDER_REQUEST,
    MESSAGE_MOVE_TIME_REQUEST,
    MESSAGE_MOVE_POSITION_REQUEST,
    MESSAGE_MOVE_DIRECTION_REQUEST,
    MESSAGE_ACTION_STATE,
    MESSAGE_TIMEOUT,
    MESSAGE_TIMER_STATE,
    MESSAGE_POSITION_STATE,

    /*MESSAGE_SENSOR_CHANGED,
    MESSAGE_MANUAL_CHANGED,
    MESSAGE_POSITION_CHANGED,
    MESSAGE_TIMEOUT_OCCURED,
    MESSAGE_TIMER_OVER,
    MESSAGE_ACTION_STATE,
    MESSAGE_OUTPUT,
    MESSAGE_CYLINDER*/

};
enum MessageFields{
    //msgCylinder
    MESSAGE_TIMEOUT_REQUEST__TIMEOUT = 0,

    MESSAGE_TIMER_REQUEST__STOP_AFTER = 0,

    MESSAGE_CYLINDER_REQUEST__CYLINDER = 0,
    MESSAGE_CYLINDER_REQUEST__DIRECTION = 1,

    MESSAGE_MOVE_TIME_REQUEST__CYLINDER = 0,
    MESSAGE_MOVE_TIME_REQUEST__DIRECTION = 1,
    MESSAGE_MOVE_TIME_REQUEST__TIMER = 2,

    MESSAGE_MOVE_POSITION_REQUEST__CYLINDER = 0,
    MESSAGE_MOVE_POSITION_REQUEST__POSITION = 1,

    MESSAGE_MOVE_DIRECTION_REQUEST__CYLINDER = 0,
    MESSAGE_MOVE_DIRECTION_REQUEST__DIRECTION = 1,

    MESSAGE_ACTION_STATE__STATE = 0,

    MESSAGE_POSITION_STATE__CYLINDER = 0,
    MESSAGE_POSITION_STATE__POSITION = 1,

};

static enum ActionState {
    ACTION_STATE_STARTING,
    ACTION_STATE_STARTED,
    ACTION_STATE_STOPPING,
    ACTION_STATE_STOPPED_OK
};

#endif //GEARRAKE_CONSTANTS_MESSAGE_H
